# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Join Author Wendy Owens Newsletter
email: me@wendyowensbooks.com
description: > # this means to ignore newlines until "baseurl:"
  Do you like to get FREE exclusives? In my newsletter I (Wendy Owens) give away free exclusive short stories as well as have occasional opportunities to get free advanced Reader Copies of some of my new releases. Sound like fun?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://signup.wendyowensbooks.com" # the base hostname & protocol for your site
twitter_username: WendyLOwens
twitter:
  username: WendyLOwens
google_site_verification: "cAfcH7-X2Arp0c2IkS8N6cbzar1pY9HDsbYEPl4dndU"

jekyll-mentions: https://twitter.com

author:
  twitter: WendyLOwens
  img: /img/wendy.jpg

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
exclude: ["_site/"]
